{
 "title": "DB Cluster Summary",
 "tags": [ "Postgres1st" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(up, environment)" } },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up\"}, service_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_start_time_seconds,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_start_time_seconds{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WARNING! Experimental Dashboard. Expand to read more.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experimental Dashboard",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "## Disclaimer \n\nThis Experimental Dashboard is not a part of the official PGF WatchTower deployment and might be updated. \nWe ship this Dashboard to obtain feedback from our users. \n\nOnce we officially release this Dashboard, it will be moved to the appropriate folder. \n\n## About Dashboard\n\nThis Dashboard is a part of the [DBaaS solution](https://docs.postgresfirst.com/dbaas) in PGF WatchTower.\nThis Dashboard displays the resource consumption in the K8s Cluster.\n"
     }
    }
   ]
  },
  { "title": "DB Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(container_start_time_seconds{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Amount of Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod) (container_memory_usage_bytes{pod=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Avg CPU Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_load_average_10s{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by () (container_fs_limit_bytes{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "RAM",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod)(container_spec_memory_limit_bytes{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} | RAM Limit"
    },
    {
     "expr": "avg by (pod)(container_memory_usage_bytes{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} | Used"
    },
    {
     "expr": "100 - clamp_max((avg by (pod) (container_memory_usage_bytes{pod=~\"$pod\"}) * 100) / avg by (pod) (container_spec_memory_limit_bytes{pod=~\"$pod\"}),100)",
     "legendFormat": "{{pod}} | Free RAM"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod)(container_memory_swap{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} | Used"
    },
    {
     "expr": "100 - clamp_max((avg by (pod) (container_memory_swap{pod=~\"$pod\"}) * 100) / avg by (pod) (container_spec_memory_swap_limit_bytes{pod=~\"$pod\"}),100)",
     "legendFormat": "{{pod}} | Free Swap"
    },
    {
     "expr": "avg by (pod)(container_spec_memory_swap_limit_bytes{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} | Swap Limit"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (pod)(container_memory_cache{pod=~\"$pod\"})",
       "legendFormat": "Cache"
      },
      {
       "expr": "avg by (pod) (increase(container_memory_failcnt{pod=~\"$pod\"}))",
       "legendFormat": "FailCnt"
      },
      {
       "expr": "avg by (pod) (increase(container_memory_failures_total{pod=~\"$pod\"}))",
       "legendFormat": "Allocation Failures"
      },
      {
       "expr": "rate(container_memory_working_set_bytes{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or irate(container_memory_working_set_bytes{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m]) ",
       "legendFormat": "Working Set"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (pod)(container_cpu_system_seconds_total{pod=~\"$pod\"} * 100) / avg by (pod) (container_cpu_usage_seconds_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} | System Usage"
    },
    {
     "expr": "avg by (pod)(container_cpu_user_seconds_total{pod=~\"$pod\"} * 100) / avg by (pod) (container_cpu_usage_seconds_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} | User Usage"
    }
   ]
  },
  {
   "title": "Total Duration of Throttling",
   "type": "graph",
   "description": "Total time duration the container has been throttled",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Total Throttled Period Intervals",
   "type": "graph",
   "description": "Number of throttled period intervals",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Intervals"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by (pod) (rate(container_cpu_cfs_periods_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[$interval]))",
       "legendFormat": "CFS Periods"
      },
      {
       "expr": "sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$pod\"}[$interval]))",
       "legendFormat": "CFS Throttled Duration"
      },
      {
       "expr": "sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\"}[$interval]))",
       "legendFormat": "CFS Throttled Periods"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps", "label": "Writes (-) / Reads (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by () (sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[$interval]) or irate(container_fs_reads_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[5m])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by () (sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[$interval]) or irate(container_fs_writes_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[5m])))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by () (rate(container_memory_swap{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or \nirate(container_memory_swap{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m]))",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "repeat": "pod",
     "yaxes": [
      { "format": "Bps", "label": "Writes (-) / Reads (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by (pod) (sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[$interval]) or irate(container_fs_reads_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[5m])))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum by (pod) (sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[$interval]) or irate(container_fs_writes_bytes_total{pod=~\"$pod\",id=~\"/kubepods.*\"}[5m])))",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum by (pod) (rate(container_memory_swap{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or \nirate(container_memory_swap{pod=~\"$pod\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m]))",
       "legendFormat": "Swap"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_receive_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_transmit_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Errors / Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(increase(container_network_transmit_errors_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]))",
     "legendFormat": "Transmit Errors"
    },
    {
     "expr": "sum(increase(container_network_transmit_packets_dropped_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]))",
     "legendFormat": "Dropped Packets"
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "repeat": "pod",
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_receive_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_transmit_bytes_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[5m]))",
       "legendFormat": "Outbound"
      },
      {
       "expr": "sum(increase(container_network_transmit_errors_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]))",
       "legendFormat": "Errors"
      },
      {
       "expr": "sum(increase(container_network_transmit_packets_dropped_total{pod=~\"$pod\",id=~\"/kubepods/.*\"}[$interval]))",
       "legendFormat": "Dropped Packets"
      }
     ]
    }
   ]
  }
 ]
}