{
 "title": "Advanced Data Exploration",
 "tags": [
  "Postgres1st",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric", "query": { "query": "metrics(.+)" } },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values($metric, node_name)"
    }
   },
   { "name": "adhoc", "label": "Ad-hoc" }
  ]
 },
 "panels": [
  {
   "title": "Metric Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "$metric", "legendFormat": "$metric" }
   ]
  },
  {
   "title": "Metric Resolution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(60/count_over_time($metric{node_name=~\"$node_name\"}[1m]))",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "View Actual Metric Values (Gauge)",
   "type": "graph",
   "description": "A gauge is a metric that represents a single numerical value that can arbitrarily go up and down.\n\nGauges are typically used for measured values like temperatures or current memory usage, but also \"counts\" that can go up and down, like the number of running goroutines.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "$metric{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "View Metric Rate of Change (Counter)",
   "type": "graph",
   "description": "A counter is a cumulative metric that represents a single numerical value that only ever goes up. A counter is typically used to count requests served, tasks completed, errors occurred, etc. Counters should not be used to expose current counts of items whose number can also go down, e.g. the number of currently running goroutines. Use gauges for this use case.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate($metric{node_name=~\"$node_name\"}[$interval])"
    }
   ]
  },
  {
   "title": "Metric Rates",
   "type": "graph",
   "description": "Shows  Number of Samples Per Second Stored for Given Interval in the Time Series",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "count_over_time($metric{node_name=~\"$node_name\"}[$interval])"
    }
   ]
  },
  {
   "title": "Metric Data Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$metric{node_name=~\"$node_name\"}"
    }
   ]
  }
 ]
}