{
 "title": "PostgreSQL Instances Overview",
 "tags": [
  "Postgres1st",
  "PostgreSQL",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "service_type", "label": "Engine", "query": "postgresql" },
   { "name": "qthres", "label": "Query Time", "query": "0.001,0.010,0.100,1,10" },
   {
    "name": "rangeCustom",
    "query": "select ($__toTime - $__fromTime)/60"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"pg_up\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\", cluster=~\"$cluster\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up{node_name=~\"$node_name\", environment=~\"$environment\", cluster=~\"$cluster\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases monitored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(min by (cluster)(pg_up{cluster!=\"\"})) or vector(0)",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(min by (service_name)(pg_up)) or vector(0)",
     "legendFormat": "Nodes"
    },
    {
     "expr": "count(min by (service_name)(pg_up{cluster=\"\"})) or vector(0)",
     "legendFormat": "Nodes without cluster"
    }
   ]
  },
  {
   "title": "Executed queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, avg by (service_name) (irate(mysql_global_status_questions{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(5, avg by (service_name) (rate(pg_stat_database_xact_commit{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval])) or \navg by (service_name) (irate(pg_stat_database_xact_commit{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(5, avg by (service_name) (rate(mongodb_op_counters_total{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\",type!=\"command\"}[$interval])) or \navg by (service_name) (irate(mongodb_op_counters_total{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\",type!=\"command\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "stat",
   "description": "*Not real time. QAN is expected to have some minutes of lag",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\r\n   FROM pmm.metrics\r\n   WHERE service_type = '${service_type}'\r\n     AND ( period_start  >= $__fromTime AND period_start <= $__toTime )\r\n    AND m_query_time_cnt > 0 AND m_query_time_sum/m_query_time_cnt > ${qthres}"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{service_type=\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\", datname!~\"template1|template0\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT period_start, service_name, avgIf(m_query_time_sum/m_query_time_cnt, m_query_time_cnt > 0) \"Execution_time\"\nFROM pmm.\"metrics\" WHERE   ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type like '%$service_type%' AND (service_name IN ($service_name)) GROUP BY period_start, service_name ORDER BY period_start ASC "
    }
   ]
  },
  {
   "title": "Lowest uptime (top 3)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "bottomk(3,range_last(mysql_global_status_uptime{service_type=\"$service_type\",service_name=~\"$service_name\"}[30s]))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "bottomk(3,range_last(pg_postmaster_uptime_seconds{service_type=\"$service_type\",service_name=~\"$service_name\"}[30s]))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "bottomk(3,range_last(mongodb_instance_uptime_seconds{service_type=\"$service_type\",service_name=~\"$service_name\"}[30s]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(period_start) as time, \r\nservice_name \"Service\", username, fingerprint \"Query\", avgIf(m_query_time_sum/m_query_time_cnt, m_query_time_cnt > 0) \"Execution_time\" FROM pmm.\"metrics\" WHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) AND ( service_type LIKE '%$service_type%' ) AND (service_name IN ($service_name)) GROUP BY service_name, username, fingerprint , m_query_time_sum, time ORDER BY time DESC LIMIT 10000"
    }
   ]
  }
 ]
}