{
 "title": "MongoDB Oplog Details",
 "tags": [
  "Postgres1st",
  "MongoDB"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "MongoDB Node",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replset\"}, service_name)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_top_commands_count{cluster=~\"$cluster\"}, database)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "current_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{set=~\"$replset\"},cluster)"
    }
   },
   {
    "name": "secondary",
    "label": "Secondary",
    "query": {
     "query": "query_result(mongodb_mongod_replset_my_state{cluster=~\"$cluster\",set=\"$replset\"}==2)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Oplog Recovery Window",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Recovery Window - $service_name",
   "type": "graph",
   "description": "This panel provides details about your recovery window over a time interval based on your oplog activities. It coordinates with replication and backup activities.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-avg by (service_name) (mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service_name\"})",
     "legendFormat": "Now to End"
    },
    {
     "expr": "avg by (service_name) (mongodb_mongod_replset_oplog_head_timestamp{service_name=~\"$service_name\"}-mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service_name\"})",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  {
   "title": "Oplog Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "description": "Repl buffer ops applied per sec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_ss_metrics_repl_buffer_apply_count{service_name=~\"$service_name\"}) or avg by (service_name) (mongodb_mongod_metrics_repl_buffer_count{service_name=~\"$service_name\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "description": "Provides information related to the number of getmore commands erlated to the local db oplog.rs collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Oplog Processing Time - $service_name",
   "type": "graph",
   "description": "Times spent per second A) pre-loading oplog ops into parallel-executable batches B) Times spent pre-loading index values and C) repl batch apply phase.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity - $service_name",
   "type": "graph",
   "description": "Provides info on the current usage and actual size of the replication buffer as defined by the maximum oplog size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_ss_metrics_repl_buffer_apply_sizeBytes{service_name=~\"$service_name\"}) or avg by (service_name) (mongodb_mongod_metrics_repl_buffer_size_bytes{service_name=~\"$service_name\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (service_name) (mongodb_ss_metrics_repl_buffer_apply_maxSizeBytes{service_name=~\"$service_name\"}) or avg by (service_name) (mongodb_mongod_metrics_repl_buffer_max_size_bytes{service_name=~\"$service_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Oplog Operations - [$service_name]",
   "type": "graph",
   "description": "Provides information on the number of write operations recorded in the oplog collection over a period of time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_preload_docs_num_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_num_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_apply_ops_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_ops_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Generation Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog GB/Hour",
   "type": "graph",
   "description": "The average amount of data in GB that the PRIMARY generate per hour",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 171 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_oplog_stats_wt_cache_bytes_written_from_cache{service_name=~\"$service_name\"}[1h]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}