{
 "title": "MongoDB Sharded Cluster Summary",
 "tags": [
  "MongoDB_HA",
  "Postgres1st"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"mongodb_up\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_rs_members_state{environment=~\"$environment\", cl_role=\"configsvr\"},cluster)"
    }
   },
   {
    "name": "shard",
    "label": "Shard Name",
    "query": {
     "query": "label_values(mongodb_mongos_db_collections_total{environment=~\"$environment\", cluster=~\"$cluster\"},shard)"
    }
   },
   {
    "name": "set",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "service_name",
    "label": "Node",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$set\"}, service_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\"},node_name)"
    }
   },
   {
    "name": "primary",
    "query": {
     "query": "query_result(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\"}==1)"
    }
   },
   {
    "name": "service_name_mongos",
    "label": "Node",
    "query": {
     "query": "label_values(mongodb_mongos_sharding_shards_total{environment=~\"$environment\",cluster=~\"$cluster\"}, service_name)"
    }
   },
   {
    "name": "cluster_role",
    "query": {
     "query": "label_values(mongodb_up, cluster_role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Config Servers",
     "type": "grafana-polystat-panel",
     "description": "Config servers store the metadata for a sharded cluster. The metadata reflects state and organization for all data and components within the sharded cluster. The metadata includes the list of chunks on every shard and the ranges that define the chunks.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "min by (member_idx) (mongodb_rs_members_state{environment=~\"$environment\",cluster=~\"$cluster\",rs_nm!~\"$shard\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mongos Routers",
     "type": "grafana-polystat-panel",
     "description": "Mongos is a routing service for MongoDB shard configurations that processes queries from the application layer, and determines the location of this data in the sharded cluster, in order to complete these operations. From the perspective of the application, a mongos instance behaves identically to any other MongoDB instance.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "max by (service_name) (mongodb_up{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name_mongos\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shard - $shard",
     "type": "grafana-polystat-panel",
     "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
     "gridPos": { "h": 5, "w": 11, "x": 7, "y": 92 },
     "repeat": "shard",
     "targets": [
      {
       "expr": "min by (member_idx) (mongodb_rs_members_state{environment=~\"$environment\",cluster=~\"$cluster\",rs_nm=~\"$shard\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "QPS of Services",
   "type": "gauge",
   "description": "Queries per second of all shards + config server replica set",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rs_nm) (rate(mongodb_op_counters_total{environment=~\"$environment\",cluster=~\"$cluster\",type!=\"command\",rs_nm!~\"\"}[$interval]) or irate(mongodb_op_counters_total{environment=~\"$environment\",cluster=~\"$cluster\",type!=\"command\",rs_nm!~\"\"}[5s]))",
     "legendFormat": "{{rs_nm}} "
    }
   ]
  },
  {
   "title": "Feature Compatibility Version",
   "type": "stat",
   "description": "Controls the compatibility version of MongoDB data files. Enabling newer version-specific features may cause datafile format to become incompatible with earlier versions of MongoDB.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (cluster) (mongodb_fcv_feature_compatibility_version{environment=~\"$environment\", cluster=~\"$cluster\"})",
     "legendFormat": "FCV"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_total{environment=~\"$environment\",cluster=~\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Mongos",
   "type": "stat",
   "description": "Number of mongos routers registered as part of the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by (service_name)(mongodb_mongos_sharding_shards_total{environment=~\"$environment\",cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Draining Shards",
   "type": "stat",
   "description": "When you run removeShard, MongoDB drains the shard by using the balancer to move the shard’s chunks to other shards in the cluster. Once the shard is drained, MongoDB removes the shard from the cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_draining_total{environment=~\"$environment\",cluster=~\"$cluster\"})",
     "legendFormat": "Draining Total"
    }
   ]
  },
  {
   "title": "DBs",
   "type": "stat",
   "description": "Total number of user-created databases",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sharding_databases_total{environment=~\"$environment\",cluster=~\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Balancer Enabled",
   "type": "stat",
   "description": "The MongoDB balancer is a background process that monitors the number of chunks on each shard. ",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_balancer_enabled{environment=~\"$environment\",cluster=~\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "stat",
   "description": "A chunk consists of a subset of sharded data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sharding_chunks_total{environment=~\"$environment\",cluster=~\"$cluster\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Last Election",
   "type": "stat",
   "description": "Time since the most recent election of any member of the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{environment=~\"$environment\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Data distribution",
   "type": "bargauge",
   "description": "Show the data distribution between all the shards involved (only user-created collections)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (mongodb_collstats_storageStats_totalSize{environment=~\"$environment\", cluster=~\"$cluster\", db!~\"admin|config|local\", rs_state=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "description": "Ops or Replicated Ops/sec classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (environment, cluster) (rate(mongodb_ss_metrics_ttl_deletedDocuments{environment=~\"$environment\", rs_nm=~\"$set\",service_name=~\"$service_name\",cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "ttl_delete"
    },
    {
     "expr": "sum by (environment, cluster, legacy_op_type) (rate(mongodb_ss_opcounters{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\",service_name=~\"$service_name\",legacy_op_type!=\"command\"}[$interval]))",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Top Hottest Collections by Read",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently read.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5,sum by (environment, cluster,database,collection) ((rate(mongodb_top_queries_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"})[$interval]) or irate(mongodb_top_queries_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"})[5s]))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Operation Latencies",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (op_type) (rate(mongodb_ss_opLatencies_latency{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_ss_opLatencies_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_ss_opLatencies_latency{environment=~\"$environment\", cluster=~\"$cluster\",service_name=~\"$service_name\"}[5m]) / (irate(mongodb_ss_opLatencies_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\"}[5m]) > 0))",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Top Hottest Collections by Write",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently written to.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5,sum by (environment,cluster,database,collection) ((rate(mongodb_top_insert_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"}+mongodb_top_remove_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"}+mongodb_top_update_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"})[$interval]) or irate(mongodb_top_insert_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"}+mongodb_top_remove_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"}+mongodb_top_update_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\"})[5m]))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Operations Per Shard",
   "type": "timeseries",
   "description": "Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_op_counters_total{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", type!=\"command\"}[5m])) by (instance) * on (instance) \ngroup_right mongodb_mongod_replset_my_state{environment=~\"$environment\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"} / mongodb_mongod_replset_my_state{environment=~\"$environment\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "MongoDB Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "min by (service_name,mongodb) ((mongodb_mongos_sharding_shards_total) * on (service_name) group_left (mongodb) (mongodb_version_info))",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (member_idx,mongodb) ((mongodb_rs_members_configVersion) * on (service_name) group_left (mongodb) (mongodb_version_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "$set Node States",
     "type": "state-timeline",
     "description": "ReplSet statuses during the select time range.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "repeat": "set",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min by (member_idx) (mongodb_rs_members_state{environment=~\"$environment\",cluster=~\"$cluster\",rs_nm=~\"$set\",service_name=~\"$service_name\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections Per Shard",
     "type": "timeseries",
     "description": "TCP connections (Incoming) in mongod processes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (rs_nm) (mongodb_connections{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", state=\"current\", rs_nm!=\"\"})",
       "legendFormat": "{{rs_nm}}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (set) (avg by (service_name,set) (mongodb_connections{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$set\", service_name=~\"$service_name\", state=\"available\"}) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{environment=~\"$environment\", cluster=~\"$cluster\", set=~\"$set\", service_name=~\"$service_name\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\"}))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collection Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Collections in Shards",
     "type": "table",
     "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "max by (rs_nm, database) (mongodb_mongod_db_collections_total{environment=~\"$environment\",cluster=\"$cluster\",database!~\"admin|config|system|local\",rs_nm=~\"$set\"})",
       "legendFormat": "{{db}} | {{rs_nm}} | Collections"
      }
     ]
    },
    {
     "title": "Size of Collections in Shards",
     "type": "table",
     "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(rs_nm, collection, database) (mongodb_collstats_storageStats_storageSize{environment=~\"$environment\", cluster=~\"$cluster\", db!~\"admin|config|local\", rs_nm=~\"$set\"})",
       "legendFormat": "{{db}} | {{shard}} | Collections"
      }
     ]
    },
    {
     "title": "Fragmentation Analysis",
     "type": "table",
     "description": "Ratio of free to allocated storage per collection. High fragmentation means disk space is wasted due to deletes and document moves. Run compact on heavily fragmented collections to reclaim it.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (environment,cluster,rs_nm,database,collection,service_name) (mongodb_collstats_storageStats_freeStorageSize{environment=~\"$environment\", cluster=~\"$cluster\",rs_nm=~\"$shard\", service_name=~\"$service_name\", db !~\"admin|config\"} /\nmongodb_collstats_storageStats_storageSize{environment=~\"$environment\", cluster=~\"$cluster\",rs_nm=~\"$shard\", service_name=~\"$service_name\", db !~\"admin|config\"}\n)",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Count of Documents in Shards",
     "type": "table",
     "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(rs_nm, collection, database) (mongodb_collstats_storageStats_count{cluster=~\"$cluster\", db!~\"admin|config|local\", rs_nm=~\"$set\"})",
       "legendFormat": "{{db}} | {{shard}} | Collections"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks in Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk distribution",
     "type": "bargauge",
     "description": "Show the chunk distribution between all the shards involved",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (shard) (last_over_time(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[1m])) / sum(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"})",
       "legendFormat": "{{shard}} "
      }
     ]
    },
    {
     "title": "Amount of Chunks in Shards",
     "type": "table",
     "description": "A chunk consists of a subset of sharded data.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "avg by (shard) (mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\",db!~\"admin|config\"})",
       "legendFormat": "{{shard}} | Chunks"
      }
     ]
    },
    {
     "title": "Dynamic of Chunks",
     "type": "timeseries",
     "description": "The sharding operation creates the initial chunk(s) to cover the entire range of the shard key values. The number of chunks created depends on the configured chunk size. After the initial chunk creation, the balancer migrates these initial chunks across the shards as appropriate as well as manages the chunk distribution going forward.",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by (shard) (rate(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[$interval]) or irate(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[5m]))",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Chunks Move Events",
     "type": "timeseries",
     "description": "MongoDB migrates chunks in a sharded cluster to distribute the chunks of a sharded collection evenly among shards. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (event) (rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*moveChunk.*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*moveChunk.*\"}[5m]))",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Chunks Split Events",
     "type": "timeseries",
     "description": "MongoDB splits chunks when they grow beyond the configured chunk size. Both inserts and updates can trigger a chunk split.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (event) (rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[5m]))",
       "legendFormat": "{{event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag by Shard",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (set) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{cluster=\"$cluster\",state!=\"ARBITER\"}[$interval])) by (service_name,set) or max(max_over_time(mongodb_mongod_replset_member_replication_lag{cluster=\"$cluster\",state!=\"ARBITER\"}[5m])) by (service_name,set))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Oplog Range by Shard",
     "type": "timeseries",
     "description": "Timespan 'window' between oldest and newest ops in the Oplog collection.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp{cluster=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{cluster=\"$cluster\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
       "legendFormat": "{{set}}"
      }
     ]
    },
    {
     "title": "Flow Control",
     "type": "timeseries",
     "description": "Flow control count and time",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max by ()(rate(mongodb_ss_flowControl_isLaggedCount{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "fc_count"
      },
      {
       "expr": "max by ()(rate(mongodb_ss_flowControl_isLaggedTimeMicros{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "fc_time"
      }
     ]
    },
    {
     "title": "Oplog GB/Hour - $service_name",
     "type": "timeseries",
     "description": "Shows the average hourly oplog data written to cache by the Primary server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
     "repeat": "service_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(mongodb_oplog_stats_wt_cache_bytes_written_from_cache{service_name=~\"$service_name\"}[1h]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "avg by (node_name)  (time() - container_start_time_seconds{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))",
       "legendFormat": "{{node_name}} | Uptime"
      },
      {
       "expr": "max by (node_name) (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} | Load"
      },
      {
       "expr": "clamp_max(avg by (node_name) (container_memory_usage_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"} * 100 / container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"}),100) or avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100)",
       "legendFormat": "{{node_name}} | Memory"
      },
      {
       "expr": "max by (node_name) (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})",
       "legendFormat": "{{node_name}} | RAM"
      },
      {
       "expr": "max by (node_name) (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}+container_spec_memory_swap_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})",
       "legendFormat": "{{node_name}} | Virtual"
      },
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))",
       "legendFormat": "{{node_name}} | Disk"
      },
      {
       "expr": "min by (node_name) (node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100",
       "legendFormat": "{{node_name}} | Min Space"
      }
     ]
    }
   ]
  }
 ]
}