{
 "title": "MongoDB Backup Details",
 "tags": [
  "Postgres1st",
  "MongoDB"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster/Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "rs_nm",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\"}, set)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Configured",
   "type": "stat",
   "description": "Check if PBM is configured with a remote backup storage",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(cluster) (mongodb_pbm_cluster_backup_configured{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR min by(cluster) (mongodb_pbm_cluster_backup_configured{environment=~\"$environment\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "PITR Status",
   "type": "stat",
   "description": "Checks if PBM oplog streaming feature for point in time recovery is enabled",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(cluster) (mongodb_pbm_cluster_pitr_backup_enabled{cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR min by(cluster) (mongodb_pbm_cluster_pitr_backup_enabled{cluster=~\"$cluster\"}) ",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Backup Agents",
   "type": "stat",
   "description": "Total number of PBM agents monitored",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", self=\"1\"}) OR count (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", replica_set=~\"$rs_nm\", self=\"1\"}) OR count (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\", self=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Successful Backup",
   "type": "stat",
   "description": "Name of the most recent successful backup",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (mongodb_pbm_backup_size_bytes{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\",status=~\"done\"}) OR max by(name) (mongodb_pbm_backup_size_bytes{environment=~\"$environment\", cluster=~\"$cluster\",status=~\"done\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Backup Agent Summary",
   "type": "piechart",
   "description": "Status of PBM agents registered with PFMM server",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_values( \"state\",min by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Agent Status",
   "type": "grafana-polystat-panel",
   "description": "Status of each PBM agent monitored",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "max by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR max by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", replica_set=~\"$rs_nm\"}) OR max by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup agent status over time",
   "type": "state-timeline",
   "description": "Status of pbm-agent over time on each node",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "min by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR min by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\", replica_set=~\"$rs_nm\"}) OR min by(host) (mongodb_pbm_agent_status{environment=~\"$environment\", cluster=~\"$cluster\"}) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Backup history",
   "type": "table",
   "description": "List of all backup jobs during the specified time range",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min by(environment, cluster, name) (mongodb_pbm_backup_size_bytes{environment=~\"$environment\", cluster=~\"$cluster\", status=~\"done|error\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by(environment, cluster, name) (mongodb_pbm_backup_duration_seconds{environment=~\"$environment\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Sizes",
   "type": "barchart",
   "description": "Size of each backup taken",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min by(environment, cluster, name) (mongodb_pbm_backup_size_bytes{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\",status=~\"done\"}) OR min by(environment, cluster, name) (mongodb_pbm_backup_size_bytes{environment=~\"$environment\", cluster=~\"$cluster\",status=~\"done\"})",
     "legendFormat": "{{environment}} - {{cluster}} - {{name}}"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "barchart",
   "description": "Time required to perform each successful backup",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(environment, cluster, name, status) (mongodb_pbm_backup_duration_seconds{environment=~\"$environment\", cluster=~\"$cluster\", replication_set=~\"$rs_nm\", status=\"done\"}) OR avg by(environment, cluster, name, status) (mongodb_pbm_backup_duration_seconds{environment=~\"$environment\", cluster=~\"$cluster\", status=\"done\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}