{
 "title": "Nodes Overview",
 "tags": [
  "OS",
  "Postgres1st",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(node_load1{node_type=~\"generic|remote_rds|container|remote\"}, region)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values(up{region=~\"$region\"}, node_type)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({region=~\"$region\",node_type=~\"$node_type\",__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions|up\"}, environment)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(up{region=~\"$region\",node_type=~\"$node_type\",environment=~\"$environment\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|up\",node_name=~\"$node_name\"}, service_name)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (node_name) (up{node_name=~\"$node_name\",region=~\"$region\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Min Node Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "DB Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (service_id) (mysql_global_status_uptime{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or \nmongodb_mongos_instance_uptime_seconds{region=~\"$region\",node_type=~\"$node_type\",node_name=~\"$node_name\"} or \npg_up{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or \npostgresql_up{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}))"
    }
   ]
  },
  {
   "title": "Min DB Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by () (mysql_global_status_uptime{node_name=~\"$node_name\"} or \nmongodb_instance_uptime_seconds {node_name=~\"$node_name\"} or \n(time() - pg_postmaster_start_time_seconds{node_name=~\"$node_name\"}))"
    }
   ]
  },
  {
   "title": "Total Virtual CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\",region=~\"$region\",node_type=~\"$node_type\"}) or \n(1-absent(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\",region=~\"$region\",node_type=~\"$node_type\"}))) + \nsum(rdsosmetrics_General_numVCPUs{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or up * 0)"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Virtual Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Disk Space Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
    }
   ]
  },
  {
   "title": "Environment Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Regions",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "count(node_load1{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or azure_resource_info{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}) by (region)"
      }
     ]
    },
    {
     "title": "Types",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "count(node_load1{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or azure_resource_info{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}) by (node_type)"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
     "targets": [
      {
       "expr": "node_load1{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or azure_resource_info{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}"
      }
     ]
    },
    {
     "title": "Regions",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "count by (region) (\nsum by (node_name,region) (label_replace(label_replace(up{node_type=~\"generic|remote_rds|container|remote\",region=~\"$region\",node_name=~\"$node_name\"},\"region\", \"$2\", \"region\", \"(.*) (..)\"),\"region\", \"$1\", \"region\", \"(..)-(.*)\")\n))",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Service Types",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "count by (service_type) (\nsum by (service_name,service_type) (max_over_time(pg_stat_database_numbackends{service_name=~\"$service_name\",service_type!=\"external\",node_name=~\"$node_name\"}[$interval]))\n)",
       "legendFormat": "PostgreSQL  "
      },
      {
       "expr": "count by (service_type) (up{service_type=\"external\",node_name=~\"$node_name\"})",
       "legendFormat": "External "
      }
     ]
    },
    {
     "title": "Services",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 22 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\",service_type!=\"external\"}[$interval]))",
       "legendFormat": "{{service_name}}     "
      },
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_connections{service_name=~\"$service_name\",state=\"current\",service_type!=\"external\"}[$interval]))",
       "legendFormat": "{{service_name}}   "
      },
      {
       "expr": "count by (service_name) (\nsum by (service_name,service_type) (max_over_time(pg_stat_database_numbackends{service_name=~\"$service_name\",service_type!=\"external\"}[$interval]))\n)",
       "legendFormat": "{{service_name}}  "
      },
      {
       "expr": "up{service_type=\"external\",service_name=~\"$service_name\"}",
       "legendFormat": "{{service_name}} ({{external_group}})"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Top Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(clamp_max(sum by (node_name) (avg by (mode,node_name)((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[5m])) )*100 or \n(max_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=~\"total\"}[$interval]) or \nmax_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=~\"total\"}[5m]) or max_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[$interval]) or \nmax_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[5m]))),100))"
    }
   ]
  },
  {
   "title": "Top Steal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(clamp_max(sum by (node_name) (avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m]))) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m])),100))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top I/O Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(clamp_max(sum by (node_name) (avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m]))))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m])) or max_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[5m]),100))"
    }
   ]
  },
  {
   "title": "Top Saturation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max by (node_name)((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(max_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Top Switches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by () (max_over_time(node_load1{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}[$interval]) or \nmax_over_time(node_load1{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top Runnable Procs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "clamp_min(max((max_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval]) - 1) or \n(max_over_time(node_procs_running{node_name=~\"$node_name\"}[5m]) -1)),0)"
    }
   ]
  },
  {
   "title": "Top Blocked Procs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(5,clamp_max(avg by (node_name) (sum by (node_name) (avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=~\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=~\"total\"}[5m]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"total\",node_type=\"remote_azure_database\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[5m]))),100))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (clamp_max(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"total\"}[5m]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[5m])),100))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "avg by (node_name) (clamp_max(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[5m])) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=~\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=~\"total\"}[5m]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",node_type=\"remote_azure_database\"}[5m]))),100))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 CPU Steal",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (node_name) (sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m])))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "CPU Steal",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "avg by (node_name) (clamp_max(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m])) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m])),100))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 CPU I/O Wait",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (node_name) (sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m])) or \nmax_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg((sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m])) or \nmax_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "CPU I/O Wait",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "avg by (node_name) ((sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m])) or \nmax_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_cpuUtilization_wait{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 CPU Saturation",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,max by (node_name)((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(max_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg(max by (node_name)((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(max_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[5m]))))",
       "legendFormat": "Average of All Hosts"
      }
     ]
    },
    {
     "title": "CPU Saturation",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "max by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or \n(max_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(aws_rds_cpu_credit_usage_average{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Context Switches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,avg by (node_name) (rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_context_switches_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Switches",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "avg by (node_name) (rate(node_context_switches_total{node_name=~\"$node_name\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Runnable Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,clamp_min(avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval]) - 1) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m]) -1)),0))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (clamp_min((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval]) - 1) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m]) -1),0))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Runnable Processes",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "clamp_min(avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval]) - 1) or \n(avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m]) -1)),0)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Blocked Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (node_name) (max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Blocked Processes",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "avg by (node_name) (max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory & Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Min Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "clamp_max(min by () (((node_memory_MemAvailable_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} + \nnode_memory_Cached_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}) * 100 or\n(100 - azure_memory_percent_average{node_name=~\"$node_name\"})),100)"
    }
   ]
  },
  {
   "title": "Min Virtual Memory Available ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(clamp_max(((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$node_name\"} * 100) / \n(node_memory_MemTotal_bytes{node_name=~\"$node_name\"} + node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}),100))"
    }
   ]
  },
  {
   "title": "Top File Cache Active Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(node_memory_Active_file_bytes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_memory_Active_file_bytes{node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_memory_cached{node_name=~\"$node_name\"}[$interval])*1024 or \nmax_over_time(rdsosmetrics_memory_cached{node_name=~\"$node_name\"}[5m])*1024)"
    }
   ]
  },
  {
   "title": "Min Swap Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(clamp_max(((max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[5m])) * 100) / \n(max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[5m])),100))"
    }
   ]
  },
  {
   "title": "Top Swap Reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096))"
    }
   ]
  },
  {
   "title": "Top Swap Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096))"
    }
   ]
  },
  {
   "title": "Memory & Swap Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Memory Percent",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "clamp_max(avg by (node_name) ((((max_over_time(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"}[5m])) or\n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + \nnode_memory_Buffers_bytes{node_name=~\"$node_name\"} + \nnode_memory_Cached_bytes{node_name=~\"$node_name\"})) /\n(max_over_time(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_memory_MemTotal_bytes{node_name=~\"$node_name\"}[$interval])))),1)",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by (node_name) (100 - azure_memory_percent_average{node_name=~\"$node_name\"})/100",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Available Virtual Memory Percent",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "clamp_max(avg by (node_name) (((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$node_name\"} * 100) / \n(node_memory_MemTotal_bytes{node_name=~\"$node_name\"} + node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})),100)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Free Swap Space Percent",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "clamp_max(avg by (node_name) (((max_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}[5m])) * 100) / \n(max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"}[5m]))),100)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Used Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"} - \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"} - \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + \nnode_memory_Buffers_bytes{node_name=~\"$node_name\"} + \nnode_memory_Cached_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Free Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)(max_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (max_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(node_memory_MemFree_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Used Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (node_name)(node_memory_MemTotal_bytes{node_name=~\"$node_name\"} + node_memory_SwapTotal_bytes{node_name=~\"$node_name\"} - \n((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$node_name\"})))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (node_memory_MemTotal_bytes{node_name=~\"$node_name\"} + node_memory_SwapTotal_bytes{node_name=~\"$node_name\"} - \n((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Available Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or \n(node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$node_name\"})",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Used Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)(node_memory_SwapTotal_bytes{node_name=~\"$node_name\"} - node_memory_SwapFree_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (node_memory_SwapTotal_bytes{node_name=~\"$node_name\"} - node_memory_SwapFree_bytes{node_name=~\"$node_name\"})",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Free Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)(node_memory_SwapFree_bytes{node_name=~\"$node_name\"}))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by()(node_memory_SwapFree_bytes{node_name=~\"$node_name\"})",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Swap In (Reads)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)(rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (rate(node_vmstat_pswpin{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Swap Out (Writes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)(rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (rate(node_vmstat_pswpout{node_name=~\"$node_name\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{node_name=~\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Min Free Space Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "clamp_max((min((node_filesystem_free_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/\nnode_filesystem_size_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"} > 0 )*100 or \n(100 - azure_storage_percent_average{node_name=~\"$node_name\"}))),100)"
    }
   ]
  },
  {
   "title": "Top I/O Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m])) + \nsum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m])) or \nsum by (node_name) ((max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m])) +\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m]))))"
    }
   ]
  },
  {
   "title": " Top Disk Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > 0  or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) /\nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) /\nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000)))"
    }
   ]
  },
  {
   "title": " Top Disk Operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) or\nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m]))+\n(rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) or\nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])))"
    }
   ]
  },
  {
   "title": " Top Disk Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[5m])))\n))"
    }
   ]
  },
  {
   "title": " Top I/O Activity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or \nirate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024))"
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Disk I/O Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,\n(sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]))) + \n(sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]))) or\nsum by (node_name) ((max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m])) +\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])))\n)",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg((sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]))) + \n(sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]))) or\nsum by (node_name) ((max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m])) +\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m]))))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Disk I/O Load",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "\n(sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]))) + \n(sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]))) or\nsum by (node_name) ((max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m])) +\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\navg by (node_name) (sum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > 0  or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) /\nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) /\nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000)) or\nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[5m]) + \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg(\nsum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > 0  or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[5m]) /\nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[5m]) /\nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000)) or\nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[5m]) + \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": " Disk Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "avg by (node_name) ((sum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > 0  or \n(rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) /\nrate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 or \n(rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) /\nrate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[5m])/1000)) or\nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[5m]) + \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Disk Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[5m])))\n))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[5m])))\n)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": " Disk Bandwidth",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "(sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$node_name\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$node_name\"}[5m])))\n)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 I/O Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)((rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024)) or \nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m]) + max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg(((rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024)) or \nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m]) + max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "I/O Activity",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "avg by (node_name)((rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) * 1024)) or \nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m]) + max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": " Top Receive Network Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m]))))"
    }
   ]
  },
  {
   "title": " Top Transmit Network Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((\n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m])))))"
    }
   ]
  },
  {
   "title": "Top Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Drop",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum by (node_name) (increase(node_network_receive_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + \nincrease(node_network_transmit_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Retransmission",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((rate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Retransmit rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[1h]) * 100 / \n(rate(node_netstat_Tcp_OutSegs{node_name=~\"$node_name\"}[1h]) + rate(node_netstat_Tcp_InSegs{node_name=~\"$node_name\"}[1h])))"
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m])))\n))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "(sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Local Network Errors",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "(sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,avg by (node_name)(rate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (rate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Retransmission",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "avg by (node_name)(rate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Local Network Drop",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by() (sum by (node_name) (increase(node_network_receive_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + \nincrease(node_network_transmit_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])))",
       "legendFormat": "Average by All Hosts"
      },
      {
       "expr": "topk(5,(sum by (node_name) (increase(node_network_receive_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + \nincrease(node_network_transmit_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]))))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Drop",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "(sum by (node_name) (increase(node_network_receive_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) + \nincrease(node_network_transmit_drop_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  }
 ]
}