{
 "title": "Processes Details",
 "tags": [
  "Postgres1st",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(node_load1{node_type=~\"generic|remote_rds|container|remote\"}, region)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values(up{region=~\"$region\"}, node_type)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({region=~\"$region\",node_type=~\"$node_type\",__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions|up\"}, environment)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(up{region=~\"$region\",node_type=~\"$node_type\",environment=~\"$environment\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of PIDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (max_over_time(node_processes_pids{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_processes_pids{node_name=~\"$node_name\"}[5m]) or\ncount by (node_name) (max_over_time(rdsosmetrics_processList_cpuUsedPc{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_processList_cpuUsedPc{node_name=~\"$node_name\"}[5m])))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Max PIDs Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) ((max_over_time(node_processes_pids{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_processes_pids{node_name=~\"$node_name\"}[5m]))/\n(max_over_time(node_processes_max_processes{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_processes_max_processes{node_name=~\"$node_name\"}[5m])))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (max_over_time(node_processes_threads{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_processes_threads{node_name=~\"$node_name\"}[5m]) or\ncount by (node_name) (count by (id,node_name)(max_over_time(rdsosmetrics_processList_rss{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_processList_rss{node_name=~\"$node_name\"}[5m])))) ",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Max Threads Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) ((max_over_time(node_processes_threads{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_processes_threads{node_name=~\"$node_name\"}[$interval]))/\n(max_over_time(node_processes_max_threads{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_processes_max_threads{node_name=~\"$node_name\"}[5m])))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Runnable Processes",
   "type": "graph",
   "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (max_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_procs_running{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_procs_running{node_name=~\"$node_name\"}[5m]) )",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Blocked Processes Waiting for I/O ",
   "type": "graph",
   "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (max_over_time(node_procs_blocked{node_name=~\"$node_name\",node_type!~\"remote_rds\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$node_name\",node_type!~\"remote_rds\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_blocked{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_blocked{node_name=~\"$node_name\"}[5m]))\n",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_procs_blocked{node_name=~\"$node_name\",node_type!~\"remote_rds\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$node_name\",node_type!~\"remote_rds\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_blocked{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_blocked{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Sleeping Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"S\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"S\"}[5m]) or \nmax_over_time(rdsosmetrics_tasks_sleeping{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_sleeping{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"S\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"S\"}[5m]) or \nmax_over_time(rdsosmetrics_tasks_sleeping{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_sleeping{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"R\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"R\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_running{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_running{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"R\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"R\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_running{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_running{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Disk Sleep Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"D\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"D\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Stopped Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"T\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"T\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_stopped{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_stopped{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"T\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"T\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_stopped{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_stopped{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Zombie Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"Z\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"Z\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_zombie{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_zombie{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"Z\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"Z\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_zombie{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_zombie{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Dead Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"X\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"X\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"X\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "$node_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }, "repeat": "node_name" },
  {
   "title": "Processes",
   "type": "graph",
   "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (node_procs_running{node_name=~\"$node_name\"})",
     "legendFormat": "Processes in runnable state"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (node_procs_blocked{node_name=~\"$node_name\"})",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "States of Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"S\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"S\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_sleeping{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_sleeping{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Sleeping"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"R\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"R\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_running{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_running{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Running"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"D\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"D\"}[5m]))",
     "legendFormat": "Disk sleep"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"T\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"T\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_stopped{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_stopped{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Stopped"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"Z\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"Z\"}[5m]) or\nmax_over_time(rdsosmetrics_tasks_zombie{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_tasks_zombie{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Zombie"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_state{node_name=~\"$node_name\",state=\"X\"}[$interval]) or \nmax_over_time(node_processes_state{node_name=~\"$node_name\",state=\"X\"}[5m]))",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "Number of PIDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (max_over_time(node_processes_pids{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_processes_pids{node_name=~\"$node_name\"}[5m]) or\ncount by (node_name) (max_over_time(rdsosmetrics_processList_cpuUsedPc{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_processList_cpuUsedPc{node_name=~\"$node_name\"}[5m])))",
     "legendFormat": "PIDs"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_max_processes{node_name=\"$node_name\"}[$interval]) or max_over_time(node_processes_max_processes{node_name=\"$node_name\"}[5m]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Percentage of max PIDs limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) ((max_over_time(node_processes_pids{node_name=\"$node_name\"}[$interval]) or max_over_time(node_processes_pids{node_name=\"$node_name\"}[5m])) /\n(max_over_time(node_processes_max_processes{node_name=\"$node_name\"}[$interval]) or max_over_time(node_processes_max_processes{node_name=\"$node_name\"}[5m])))",
     "legendFormat": "PIDs"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (max_over_time(node_processes_threads{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(node_processes_threads{node_name=~\"$node_name\"}[5m]) or\ncount by (node_name) (count by (id,node_name)(max_over_time(rdsosmetrics_processList_rss{node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_processList_rss{node_name=~\"$node_name\"}[5m])))) ",
     "legendFormat": "Threads"
    },
    {
     "expr": "avg by (node_name) (max_over_time(node_processes_max_threads{node_name=\"$node_name\"}[$interval]) or max_over_time(node_processes_max_threads{node_name=\"$node_name\"}[5m]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Percentage of max threads limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) ((max_over_time(node_processes_threads{node_name=\"$node_name\"}[$interval]) or max_over_time(node_processes_threads{node_name=\"$node_name\"}[5m])) /\n(max_over_time(node_processes_max_threads{node_name=\"$node_name\"}[$interval]) or max_over_time(node_processes_max_threads{node_name=\"$node_name\"}[5m])))",
     "legendFormat": "PIDs"
    }
   ]
  }
 ]
}