# Documentation Makefile.

DIR := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

doc-check-images:   ## Check if all images are used in documentation
	@$(DIR)/resources/bin/check-images.sh

doc-remove-images:  ## Remove unused images from documentation
	@ACTION=remove $(DIR)/resources/bin/check-images.sh

doc-build:          ## Build documentation (used in CI)
	# This command is used to build and deploy a preview to onrender.com
	# Preview URL: https://pmm-doc.onrender.com

	mkdocs build -f $(DIR)/mkdocs.yml

doc-build-pdf:      ## Build documentation in PDF format
	docker run --rm -v $(DIR):/docs -w /build perconalab/pmm-doc-md:latest \
		bash -c " \
			cp -r /docs/* /build/ && \
			git init && \
			git config user.email 'doc-team@percona.com' && \
			git add --all && \
			git commit -am 'Initial commit' > /dev/null && \
			mkdocs build -f mkdocs-pdf.yml && \
			cp /build/site/pdf/*.pdf /docs/ \
		"

doc-build-image:    ## Build perconalab/pmm-doc-md:latest image
	# @docker buildx build --progress=plain -t perconalab/pmm-doc-md:latest -f documentation/resources/Dockerfile.build .

doc-build-preview:  ## Build documentation and preview at http://localhost:8000
	docker run --rm -p 8000:8000 -v $(DIR):/docs -w /build perconalab/pmm-doc-md:latest \
	  bash -c " \
			cp -r /docs/* /build/ && \
			git init && \
			git config user.email 'doc-team@percona.com' && \
			git add --all && \
			git commit -am 'Initial commit' > /dev/null && \
			mkdocs serve -f mkdocs.yml --dev-addr=0.0.0.0:8000 \
		"
doc-search-icons:     ## Search for icons that can be used in documentation
	@open https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
